#
# Continuous Integration (CI) - Internal
# This pipeline builds and validate the app for all supported architectures, in a production
# configuration. This pipeline relies on Microsoft-internal resources to run.
#

trigger:
- manual
pr: none

name: 0.$(Date:yyMM).$(DayOfMonth)$(Rev:rr).0

jobs:
- template: build/pipelines/templates/build-single-architecture.yaml
  parameters:
    isReleaseBuild: true
    useReleaseAppxManifest: false
    platform: x64



- template: build/pipelines/templates/package-appxbundle.yaml