#
# Release
# This pipeline builds a version of the app in a production configuration to be released to the
# Store and the Windows image. This pipeline relies on Microsoft-internal resources to run.
#

trigger: none
pr: none

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'



jobs:
- template: build/pipelines/templates/build-single-architecture.yaml
  parameters:
    platform: x64
    isReleaseBuild: true
    useReleaseAppxmanifest: true



- template: build/pipelines/templates/run-unit-tests.yaml
  parameters:
    platform: x64



- template: build/pipelines/templates/package-appxbundle.yaml
  parameters:
    signBundle: true
    createStoreBrokerPackages: true

- template: build/pipelines/templates/release-store.yaml
- template: build/pipelines/templates/release-vpack.yaml